### ISSUE TITLE
Txt + requirements problem

### ISSUE THREAD

**Issue by headering** [NeusZimmer/ONNX-ModularUI-StableDiffusion#2]
Add ".txt" to additional_requirements file and mention in guide that VS c++ 14.0 build tool required to install (to build that additional stuff)

VS build tools: https://aka.ms/vs/17/release/vs_BuildTools.exe

**Comment by NeusZimmer** [comment]
Thanks for the feedback, I tested without Vs installed, which component do you mean needed the VS tools, i will re-check it.

**Comment by NeusZimmer** [comment]
Thanks for the feedback, i will check the needs for insightface package. I check with a clean install without VS installed in my environment, but maybe the package was already in the cache...

**Comment by NeusZimmer** [comment]
Added info on install instructions
